name: Recology
description: An exploration of using R for ecology, evolution, and open science.
url: http://schamberlain.github.com
paginate: 5
pygments: true
markdown: rdiscount
permalink: /:year/:month/:title/
