#+TITLE:     Reflections on a class with Prof Bob Haining
#+AUTHOR:    ivan hanigan
#+EMAIL:     ivan_hanigan@Django
#+DATE:      2013-04-05
#+LaTeX_HEADER: \usepackage{amssymb,amsmath}

* Introduction
I recently attended a class on spatial regression with Prof Bob Haining.  
He described the issue of spatially correlated errors and the problems this poses.

Simplistically I took away the following messages:

* Beta is OK but SE may be biased

A standard regression model assumes independent errors:

$Y_{i} = \beta_{0} + \beta_{1} X_{1i} + e_{i}$

But with spatial data it is likely that the errors are spatially correlated.  
This is likely to mean the point estimate of beta 1 is OK but the Standard Error is wrong.

* The Spatial Error Model
So we could model allowing for correlated errors:

$Y_{i} = \beta_{0} + \beta_{1} X_{1i} + \eta_{i}$

Where:

$\eta_{i}$ = Spatially autocorrelated errors.

* The Spatial Lag Model
Or we could include a term for the neighbours, thus absorbing the correlated errors:

$Y_{i} = \beta_{0} + \beta_{1} X_{1i} + \rho(Neighbours Y_{ij}) + e_{i}$

Where:

$\rho_(Neighbours Y_{ij})$ = is an additional explanatory variable which is the value of the dependent variable in neighbouring areas. 

* Spatially Lagged Independent Variable(s)
Then we could include a term for the exposure variable in the neighbours:

$Y_{i} = \beta_{0} + \beta_{1} X_{1i} + \beta_{2L} X_{2ij} + e_{i}$

Where:

$\beta_{2L} X_{2ij}$ = is the independent variable X2 that is spatially lagged.

* Discussion

Stay tuned.

